version: '2.2'

services: 
  nginx:
    build:
      context:  ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    ports:
      - 80:80
  mariadb :
    build:
      context:  requirements/mariadb
      dockerfile: Dockerfile
    image : mariadb
    container_name: mariadb
  wordpress :
    build:
      context:  requirements/wordpress
      dockerfile: Dockerfile
    image : wordpress
    container_name: wordpress 
    volumes:
      - wordpress: /var/www/html/wordpress

