version: '3'

services: 
  mariadb :
    build: ./requirements/mariadb
    image : mariadb
    container_name: mariadb
    restart: always
    volumes:
        - wordpress:/var/www/html/wordpress
    env_file:
        - .env
    networks:
        - wordpress
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    init : true

  wordpress:
    build:
      context:  ./requirements/wordpress
    image : wordpress
    container_name: wordpress 
    volumes:
        - wordpress:/var/www/html/wordpress
    env_file:
        - .env
    networks:
        - wordpress
    depends_on:
        - mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    ports:
        - 9000:9000
    restart: always
    init : true


  nginx:
    build:
      context:  ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    networks:
        - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    init : true
    
  

volumes:
  wordpress:

networks:
  wordpress: