
version: '2.2'

services: 
  nginx:
    build:
      context:  ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    ports:
      - 80:80
  mariadb :
    build:
      context:  requirements/mariadb
      dockerfile: Dockerfile
    image : mariadb
  wordpress :
    build:
      context:  requirements/wordpress
      dockerfile: Dockerfile
    image : wordpress

