version: '3'

services: 
  mariadb :
    build: ./requirements/mariadb
    image : mariadb
    container_name: mariadb
    restart: always
    volumes:
        - mariadb:/var/lib/mysql
        #           - wordpress:/var/www/html/wordpress
    env_file:
        - .env
    networks:
        - wordpress
    environment:
        - MYSQL_DATABASE=wordpress
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          #        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  wordpress:
    build:
      context:  ./requirements/wordpress
    image : wordpress
    container_name: wordpress 
    volumes:
        - wordpress:/var/www/html/wordpress
    env_file:
        - .env
    networks:
        - wordpress
    depends_on:
        - mariadb
    environment:
        - WORDPRESS_DB_HOST=mariadb:3306
        - WORDPRESS_DB_NAME=wordpress
        - WORDPRESS_DB_USER=$MYSQL_USER
        - WORDPRESS_DB_PASSWORD=$MYSQL_USER
          #        - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
          #        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          #        - MYSQL_DATABASE=${MYSQL_DATABASE}
          #        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - 9000:9000
    restart: always

  nginx:
    depends_on:
        - wordpress
    build:
      context:  ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    networks:
        - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    
  

volumes:
  wordpress:

networks:
  wordpress:
