version: '3'

services: 
  mariadb :
    build:
      context: ./requirements/mariadb
      dockerfile : Dockerfile
    container_name: mariadb
    restart: always
    volumes:
        - mariadb:/var/lib/mysql
        - wordpress:/var/www/html/wordpress
    env_file:
        - .env
    networks:
        - wordpress
    environment:
        - MYSQL_HOST=localhost
        - MYSQL_DATABASE=wordpress
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          #        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - 3306:3306

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress 
    volumes:
        - wordpress:/var/www/html/wordpress
    env_file:
        - .env
    networks:
        - wordpress
    depends_on:
        - mariadb
    environment:
        - WORDPRESS_DB_HOST=mariadb:3306
        - WORDPRESS_DB_NAME=wordpress
        - WORDPRESS_DB_USER=$MYSQL_USER
        - WORDPRESS_DB_PASSWORD=$MYSQL_USER
          #        - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
          #        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          #        - MYSQL_DATABASE=${MYSQL_DATABASE}
          #        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
         - 9000:9000
    restart: always

  nginx:
    depends_on:
        - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    networks:
        - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always

volumes:
  wordpress:
  mariadb:

networks:
  wordpress:
      driver: bridge
