version: '3'

services: 
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:local
    container_name: wordpress 
    volumes:
        - wordpress:/var/www/html/wordpress
    env_file:
        - .env
    networks:
        - wordpress
    depends_on:
        - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:local
    container_name: mariadb
    restart: always
    volumes:
        - mariadb:/var/lib/mysql
    env_file:
        - .env
    networks:
        - wordpress
  nginx:
    depends_on:
        - wordpress
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: nginx:local
    container_name: nginx
    networks:
        - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always

volumes:
  wordpress:
  mariadb:

networks:
  wordpress:
      driver: bridge
